/**
 * Everything that reads or writes Google Home automation scripts (the YAML
 * used by the script editor at https://home.google.com) lives in this file.
 * The app can't talk to Google Home directly, so schedules travel as scripts
 * the user copies in and out. A future direct Google Home connection should
 * replace this module behind the same exported functions.
 */
import { load } from 'js-yaml';

import { DAYS, normalizeTime, parseDay, sortDays } from './days';
import { newId } from './id';
import { addEvent } from './schedule';
import type { Day, Device } from './types';

export const GOOGLE_HOME_URL = 'https://home.google.com';

const SCRIPT_NAME = 'Home app schedules';
const SCRIPT_DESCRIPTION = 'Generated by home app';

// ---------------------------------------------------------------------------
// Device names

/** The name Google Home scripts use for a device: "Kettle - Kitchen". */
export function deviceRef(device: Pick<Device, 'name' | 'room'>): string {
  const name = device.name.trim();
  const room = device.room.trim();
  return room ? `${name} - ${room}` : name;
}

/** Splits "Kettle - Kitchen" into name and room (room may be empty). */
export function parseDeviceRef(ref: string): { name: string; room: string } {
  const text = ref.trim();
  const at = text.lastIndexOf(' - ');
  if (at <= 0) return { name: text, room: '' };
  return { name: text.slice(0, at).trim(), room: text.slice(at + 3).trim() };
}

// ---------------------------------------------------------------------------
// Export

const YAML_RESERVED = /^(true|false|yes|no|on|off|null|~|y|n)$/i;
const YAML_PLAIN_SAFE = /^[A-Za-z0-9][A-Za-z0-9 _.,()'&/+-]*$/;

/** Writes a string as a plain YAML scalar when safe, otherwise double-quoted. */
function yamlString(value: string): string {
  if (YAML_PLAIN_SAFE.test(value) && !YAML_RESERVED.test(value) && !/\s$/.test(value)) {
    return value;
  }
  return JSON.stringify(value); // JSON strings are valid double-quoted YAML.
}

type Automation = { time: string; days: Day[]; on: boolean; device: string };

/** One automation per device, time and action, covering all its weekdays. */
function collectAutomations(devices: Device[]): Automation[] {
  const automations: Automation[] = [];
  for (const device of devices) {
    const byKey = new Map<string, Automation>();
    for (const event of device.events) {
      const key = `${event.time}|${event.on}`;
      const existing = byKey.get(key);
      if (existing) existing.days = sortDays([...existing.days, ...event.days]);
      else byKey.set(key, { time: event.time, on: event.on, days: sortDays(event.days), device: deviceRef(device) });
    }
    automations.push(...[...byKey.values()].filter((a) => a.days.length > 0));
  }
  return automations.sort(
    (a, b) => a.time.localeCompare(b.time) || a.device.localeCompare(b.device) || Number(b.on) - Number(a.on)
  );
}

/** Builds one Google Home script covering every device's schedule. */
export function buildScript(devices: Device[]): string {
  const lines = [
    'metadata:',
    `  name: ${yamlString(SCRIPT_NAME)}`,
    `  description: ${yamlString(SCRIPT_DESCRIPTION)}`,
  ];
  const automations = collectAutomations(devices);
  if (automations.length === 0) {
    lines.push('automations: []');
    return lines.join('\n') + '\n';
  }
  lines.push('automations:');
  for (const a of automations) {
    lines.push(
      '  - starters:',
      '      - type: time.schedule',
      `        at: "${a.time}"`,
      `        weekdays: [${a.days.join(', ')}]`,
      '    actions:',
      '      - type: device.command.OnOff',
      `        devices: ${yamlString(a.device)}`,
      `        on: ${a.on}`
    );
  }
  return lines.join('\n') + '\n';
}

export function countAutomations(devices: Device[]): number {
  return collectAutomations(devices).length;
}

// ---------------------------------------------------------------------------
// Import

export type ImportedEvent = {
  /** Device reference as written in the script, e.g. "Kettle - Kitchen". */
  device: string;
  time: string;
  on: boolean;
  days: Day[];
};

export type ImportResult = {
  events: ImportedEvent[];
  /** Human-readable notes about anything that was skipped or ignored. */
  issues: string[];
};

type YamlMap = Record<string, unknown>;

function isMap(value: unknown): value is YamlMap {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function asList(value: unknown): unknown[] {
  if (value === undefined || value === null) return [];
  return Array.isArray(value) ? value : [value];
}

function describe(value: unknown): string {
  const text = typeof value === 'string' ? value : JSON.stringify(value);
  return text.length > 60 ? `${text.slice(0, 57)}...` : text;
}

function parseOn(value: unknown): boolean | null {
  if (typeof value === 'boolean') return value;
  if (typeof value === 'string') {
    const v = value.trim().toLowerCase();
    if (['true', 'on', 'yes'].includes(v)) return true;
    if (['false', 'off', 'no'].includes(v)) return false;
  }
  return null;
}

/** Finds the list of automations however the pasted script is shaped. */
function findAutomations(doc: unknown): unknown[] | null {
  if (Array.isArray(doc)) return doc;
  if (!isMap(doc)) return null;
  if ('automations' in doc) return asList(doc.automations);
  if ('starters' in doc || 'actions' in doc) return [doc];
  return null;
}

/**
 * Reads a script copied from the Google Home script editor and returns the
 * On/Off schedule events it contains. Anything that can't be represented
 * (other starters, conditions, other actions) is listed in `issues`.
 */
export function parseScript(text: string): ImportResult {
  const issues: string[] = [];
  const events: ImportedEvent[] = [];

  let doc: unknown;
  try {
    doc = load(text);
  } catch (e) {
    const message = e instanceof Error ? e.message.split('\n')[0] : String(e);
    return { events, issues: [`The script isn't valid YAML: ${message}`] };
  }

  const automations = findAutomations(doc);
  if (!automations) {
    return { events, issues: ['No "automations:" section was found in the script.'] };
  }

  automations.forEach((automation, index) => {
    const label = `Automation ${index + 1}`;
    if (!isMap(automation)) {
      issues.push(`${label}: not understood (${describe(automation)}).`);
      return;
    }

    const schedules: { time: string; days: Day[] }[] = [];
    for (const starter of asList(automation.starters)) {
      if (!isMap(starter) || starter.type !== 'time.schedule') {
        const type = isMap(starter) ? starter.type : starter;
        issues.push(`${label}: starter "${describe(type)}" isn't a time schedule, so it was ignored.`);
        continue;
      }
      const time = typeof starter.at === 'string' ? normalizeTime(starter.at) : null;
      if (!time) {
        issues.push(`${label}: time "${describe(starter.at)}" isn't a clock time (sunrise and sunset aren't supported), so it was ignored.`);
        continue;
      }
      let days: Day[] = DAYS;
      if (starter.weekdays !== undefined) {
        const parsed: Day[] = [];
        for (const raw of asList(starter.weekdays)) {
          const day = parseDay(raw);
          if (day) parsed.push(day);
          else issues.push(`${label}: weekday "${describe(raw)}" wasn't recognised.`);
        }
        days = sortDays(parsed);
      }
      if (days.length === 0) {
        issues.push(`${label}: the ${time} starter has no usable weekdays, so it was ignored.`);
        continue;
      }
      schedules.push({ time, days });
    }

    if (automation.condition !== undefined || automation.conditions !== undefined) {
      issues.push(`${label}: conditions aren't supported and were ignored.`);
    }

    const switches: { device: string; on: boolean }[] = [];
    for (const action of asList(automation.actions)) {
      if (!isMap(action) || action.type !== 'device.command.OnOff') {
        const type = isMap(action) ? action.type : action;
        issues.push(`${label}: action "${describe(type)}" isn't an On/Off command, so it was ignored.`);
        continue;
      }
      const on = parseOn(action.on);
      if (on === null) {
        issues.push(`${label}: On/Off action has no valid "on" value (${describe(action.on)}).`);
        continue;
      }
      const devices = asList(action.devices).filter((d): d is string => typeof d === 'string' && d.trim() !== '');
      if (devices.length === 0) {
        issues.push(`${label}: On/Off action has no devices.`);
        continue;
      }
      for (const device of devices) switches.push({ device: device.trim(), on });
    }

    if (schedules.length === 0 || switches.length === 0) {
      issues.push(`${label}: skipped, because it needs both a time schedule starter and an On/Off action.`);
      return;
    }
    for (const s of schedules) {
      for (const sw of switches) events.push({ device: sw.device, on: sw.on, ...s });
    }
  });

  return { events, issues };
}

function findDevice(devices: Device[], ref: string): Device | undefined {
  const { name, room } = parseDeviceRef(ref);
  const lower = (s: string) => s.trim().toLowerCase();
  const exact = devices.find((d) => lower(deviceRef(d)) === lower(ref));
  if (exact) return exact;
  if (!room) {
    const byName = devices.filter((d) => lower(d.name) === lower(name));
    if (byName.length === 1) return byName[0];
  }
  return undefined;
}

/** Existing devices that the import would add events to and that already have events. */
export function devicesWithExistingEvents(devices: Device[], imported: ImportedEvent[]): Device[] {
  const hit = new Set<Device>();
  for (const e of imported) {
    const device = findDevice(devices, e.device);
    if (device && device.events.length > 0) hit.add(device);
  }
  return [...hit];
}

/**
 * Adds imported events to the matching devices, creating devices that don't
 * exist yet. With `replace`, matched devices lose their current events first.
 */
export function applyImport(
  devices: Device[],
  imported: ImportedEvent[],
  replace: boolean
): { devices: Device[]; created: string[] } {
  const result = devices.map((d) => ({ ...d, events: [...d.events] }));
  const created: string[] = [];
  const cleared = new Set<string>();

  for (const e of imported) {
    let device = findDevice(result, e.device);
    if (!device) {
      device = { id: newId(), ...parseDeviceRef(e.device), events: [] };
      result.push(device);
      created.push(deviceRef(device));
    } else if (replace && !cleared.has(device.id)) {
      device.events = [];
    }
    cleared.add(device.id);
    device.events = addEvent(device.events, { time: e.time, on: e.on, days: e.days });
  }
  return { devices: result, created };
}
